//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class AwardsPlayers
    {
        public string playerID { get; set; }
        public string awardID { get; set; }
        public int yearID { get; set; }
        public string lgID { get; set; }
        public string tie { get; set; }
        public string notes { get; set; }
    }
}
