//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Fielding
    {
        public string playerID { get; set; }
        public int yearID { get; set; }
        public int stint { get; set; }
        public string teamID { get; set; }
        public string lgID { get; set; }
        public string POS { get; set; }
        public Nullable<int> G { get; set; }
        public Nullable<int> GS { get; set; }
        public Nullable<int> InnOuts { get; set; }
        public Nullable<int> PO { get; set; }
        public Nullable<int> A { get; set; }
        public Nullable<int> E { get; set; }
        public Nullable<int> DP { get; set; }
        public Nullable<int> PB { get; set; }
        public Nullable<int> WP { get; set; }
        public Nullable<int> SB { get; set; }
        public Nullable<int> CS { get; set; }
        public Nullable<int> ZR { get; set; }
    }
}
