//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class FieldingOF
    {
        public string playerID { get; set; }
        public int yearID { get; set; }
        public int stint { get; set; }
        public Nullable<int> Glf { get; set; }
        public Nullable<int> Gcf { get; set; }
        public Nullable<int> Grf { get; set; }
    }
}
