//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pitching
    {
        public string playerID { get; set; }
        public int yearID { get; set; }
        public int stint { get; set; }
        public string teamID { get; set; }
        public string lgID { get; set; }
        public Nullable<int> W { get; set; }
        public Nullable<int> L { get; set; }
        public Nullable<int> G { get; set; }
        public Nullable<int> GS { get; set; }
        public Nullable<int> CG { get; set; }
        public Nullable<int> SHO { get; set; }
        public Nullable<int> SV { get; set; }
        public Nullable<int> IPouts { get; set; }
        public Nullable<int> H { get; set; }
        public Nullable<int> ER { get; set; }
        public Nullable<int> HR { get; set; }
        public Nullable<int> BB { get; set; }
        public Nullable<int> SO { get; set; }
        public Nullable<int> BAOpp { get; set; }
        public Nullable<int> ERA { get; set; }
        public Nullable<int> IBB { get; set; }
        public Nullable<int> WP { get; set; }
        public Nullable<int> HBP { get; set; }
        public Nullable<int> BK { get; set; }
        public Nullable<int> BFP { get; set; }
        public Nullable<int> GF { get; set; }
        public Nullable<int> R { get; set; }
        public Nullable<int> SH { get; set; }
        public Nullable<int> SF { get; set; }
        public Nullable<int> GIDP { get; set; }
    }
}
