//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class SchoolsPlayers
    {
        public string playerID { get; set; }
        public string schoolID { get; set; }
        public Nullable<int> yearMin { get; set; }
        public Nullable<int> yearMax { get; set; }
    }
}
