//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class SeriesPost
    {
        public int yearID { get; set; }
        public string round { get; set; }
        public string teamIDwinner { get; set; }
        public string lgIDwinner { get; set; }
        public string teamIDloser { get; set; }
        public string lgIDloser { get; set; }
        public Nullable<int> wins { get; set; }
        public Nullable<int> losses { get; set; }
        public Nullable<int> ties { get; set; }
    }
}
