//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class TeamsHalf
    {
        public int yearID { get; set; }
        public string lgID { get; set; }
        public string teamID { get; set; }
        public string half { get; set; }
        public string divID { get; set; }
        public string DivWin { get; set; }
        public Nullable<int> rank { get; set; }
        public Nullable<int> G { get; set; }
        public Nullable<int> W { get; set; }
        public Nullable<int> L { get; set; }
    }
}
